### ISSUE TITLE
importing completely offline

### ISSUE THREAD

**Issue by OllyHill** [rxwx/chlonium#4]
Mate, thanks for a lovely project. Agree completely that importing cookies can be so difficult.

My question is, is there a way to obtain the chrome master key completely offline? On a recent engagement, i have the windows
master keys, local state file, and cookies file, but cannot run the first app on the clients computer to decode the chrome master key.

Cheers.
Olly

**Comment by rxwx** [comment]
Addressed in 8d99dd2
