### ISSUE TITLE
Unable to Select Chrome

### ISSUE THREAD

**Issue by OllyHill** [rxwx/chlonium#6]
Thank you so much mate for adding offline decryption. It's been truly lovely.

I am using the latest code and cannot select Chrome as the browser to import to. Edge is always an option, but Chrome is not. I wish I could provide more details, but cannot clue in to the issue. Have you seen this?

A little tidbit if it matters, Chrome has moved the Cookies file to the Network folder. 

This app has been a lifesaver mate. All props to you.

**Comment by rxwx** [comment]
Fixed in 7faccfa
